version: '2.0'

services:
  healthcheck:
    container_name: healthcheck
    hostname: healthcheck
    build:
      context: ./
      args:
        http_port: 80
        ftp_port: 21
        root_path: "/wwwroot"
        extra_packages: ""
    restart: always
    ports:
      - "8888:80"    # http
      - "2121:21"    # ftp
    volumes:
      - "/home/po/workspace/lavalab-ci-box/lava-healthchecks-binary/mainline:/wwwroot/healthcheck/mainline/"
      - "/home/po/workspace/lavalab-ci-box/lava-healthchecks-binary/images:/wwwroot/healthcheck/images/"

